src/Entity/Detailcommande.php
<?php

namespace App\Entity;

use App\Entity\Consommable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DetailcommandeRepository;

#[ORM\Entity(repositoryClass: DetailcommandeRepository::class)]
class Detailcommande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prix = null;

    #[ORM\ManyToOne(inversedBy: 'detailcommandes')]
    private ?Consommable $Consommable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dimension = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $createAlt = null;

    #[ORM\ManyToOne(inversedBy: 'detailcommandes')]
    private ?Commande $commande = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $qteconsommable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $qtecommande = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getConsommable(): ?Consommable
    {
        return $this->Consommable;
    }

    public function setConsommable(?Consommable $Consommable): static
    {
        $this->Consommable = $Consommable;

        return $this;
    }

    public function getDimension(): ?string
    {
        return $this->dimension;
    }

    public function setDimension(?string $dimension): static
    {
        $this->dimension = $dimension;

        return $this;
    }

    public function getCreateAlt(): ?\DateTimeInterface
    {
        return $this->createAlt;
    }

    public function setCreateAlt(?\DateTimeInterface $createAlt): static
    {
        $this->createAlt = $createAlt;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): static
    {
        $this->commande = $commande;

        return $this;
    }

    public function getQteconsommable(): ?string
    {
        return $this->qteconsommable;
    }

    public function setQteconsommable(?string $qteconsommable): static
    {
        $this->qteconsommable = $qteconsommable;

        return $this;
    }

    public function getQtecommande(): ?string
    {
        return $this->qtecommande;
    }

    public function setQtecommande(?string $qtecommande): static
    {
        $this->qtecommande = $qtecommande;

        return $this;
    }
}

src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Entity\Commande;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FactureRepository;

#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Reference = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $montant = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $moyenpaiemant = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $datefacture = null;

    #[ORM\Column(nullable: true)]
    private ?float $TVA = null;

    #[ORM\ManyToOne(inversedBy: 'factures')]
    private ?Commande $Commande = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $resteapayer = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(?string $Reference): static
    {
        $this->Reference = $Reference;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(?string $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMoyenpaiemant(): ?string
    {
        return $this->moyenpaiemant;
    }

    public function setMoyenpaiemant(?string $moyenpaiemant): static
    {
        $this->moyenpaiemant = $moyenpaiemant;

        return $this;
    }

    public function getDatefacture(): ?\DateTimeInterface
    {
        return $this->datefacture;
    }

    public function setDatefacture(?\DateTimeInterface $datefacture): static
    {
        $this->datefacture = $datefacture;

        return $this;
    }

    public function getTVA(): ?float
    {
        return $this->TVA;
    }

    public function setTVA(?float $TVA): static
    {
        $this->TVA = $TVA;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): static
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function __tostring()
    {
        $date=$this->getDatefacture();
        $dateformat= $date->format('d/m/y');
        return $dateformat;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getResteapayer(): ?string
    {
        return $this->resteapayer;
    }

    public function setResteapayer(?string $resteapayer): static
    {
        $this->resteapayer = $resteapayer;

        return $this;
    }
}

src/Controller/DetailcommandeController.php
<?php

namespace App\Controller;

use App\Entity\Facture;
use App\Entity\Commande;
use App\Form\FactureType;
use App\Entity\Detailcommande;
use App\Form\DetailcommandeType;
use App\Repository\ClientRepository;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ConsommableRepository;
use App\Repository\DetailcommandeRepository;
use App\Repository\FactureRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/detailcommande')]
final class DetailcommandeController extends AbstractController
{
    #[Route(name: 'app_detailcommande_index', methods: ['GET'])]
    public function index(DetailcommandeRepository $detailcommandeRepository): Response
    {
        return $this->render('detailcommande/index.html.twig', [
            'detailcommandes' => $detailcommandeRepository->findAll(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_detailcommande_new', methods: ['GET', 'POST'])]
    public function new(ConsommableRepository $consommableRepository, SessionInterface $session, $id, Request $request, EntityManagerInterface $em, ClientRepository $clientRepository): Response
    {

        $commande = new Commande();
        $form = $this->createForm(DetailcommandeType::class);
        $form->handleRequest($request);
        $client = $clientRepository->find($id);
        //recuperer les detail commande existant dans la session
        $details = $session->get('details_commande', []);


        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->getClickedButton()->getName() == 'autre') {
                $details[] = [
                    'form' => $request->request->all()
                ];
                $session->set('details_commande', $details);
                return $this->redirectToRoute('app_detailcommande_new', ['id' => $id], Response::HTTP_SEE_OTHER);
            }
            $details[] = [
                'form' => $request->request->all()
            ];
            $session->set('details_commande', $details);
            $details = $session->get('details_commande', []);
            $commande = new Commande();
            $client = $clientRepository->find($id);

            $commande->setClient($client);
            $commande->setDescription('...');
            $commande->setStatutcommande('en cours');
            $commande->setCreated(new \DateTime());

            $prixcommande = 0;

            foreach ($details as $detail) {
                $detailcommande = new Detailcommande();

                $detailcommande->setDescription($detail['form']['detailcommande']['description']);
                $detailcommande->setPrix($detail['form']['detailcommande']['prix']);
                $detailcommande->setType($detail['form']['detailcommande']['type']);
                $detailcommande->setCommande($commande);
                $detailcommande->setQteconsommable($detail['form']['detailcommande']['qteconsommable']);
                $detailcommande->setQtecommande($detail['form']['detailcommande']['qtecommande']);
                $detailcommande->setDimension($detail['form']['detailcommande']['dimension']);
                $detailcommande->setCreateAlt(new \DateTime());

                // mise a jour de l'approvisionnement
                $consommable = $consommableRepository->find($detail['form']['detailcommande']['consommable']);
                $consommableQteRestant = $consommable->getQtedispo();
                if ($consommableQteRestant < $detail['form']['detailcommande']['qteconsommable']) {
                    $this->addFlash('warring', 'Quantite restant est insuffisant');
                }
                $consommable->setQtedispo($consommableQteRestant - $detail['form']['detailcommande']['qteconsommable']);
                $detailcommande->setConsommable($consommable);
                $prixcommande = +$detail['form']['detailcommande']['prix'] * $detail['form']['detailcommande']['qtecommande'];
                $em->persist($detailcommande);
            }

            $commande->setPrixcommande($prixcommande);
            $em->persist($commande);
            $em->flush();

            $session->remove('details_commande');
            return $this->redirectToRoute('app_detailcommande_show', ['idcommande' => $commande->getId()], Response::HTTP_SEE_OTHER);
        }


        return $this->render('detailcommande/new.html.twig', [
            'form' => $form,
            'client' => $client
        ]);
    }

    #[Route('/delete/{index}/{id}', name: 'detail_commande_delete', methods: ['POST'])]
    public function detail_commande_delete(int $index, $id, SessionInterface $session): Response
    {
        //recuperer la liste des details
        $details = $session->get('details_commande', []);
        //verifier si l'index existe
        if (isset($details[$index])) {
            unset($details[$index]);
            $session->set('details_commande', array_values($details));
            # code...
        }
        return $this->redirectToRoute('app_detailcommande_new', ['id' => $id], Response::HTTP_SEE_OTHER);
    }

    #[Route('/save/{id}', name: 'app_detailcommande_save', methods: ['GET'])]
    public function save($id, ConsommableRepository $consommableRepository, SessionInterface $session, Request $request, EntityManagerInterface $em, ClientRepository $clientRepository): Response
    {
        $details = $session->get('details_commande', []);
        $detailcommande = new Detailcommande();
        $commande = new Commande();
        $client = $clientRepository->find($id);

        $commande->setClient($client);
        $commande->setStatutcommande('en cours');
        $commande->setCreated(new \DateTime());
        $lastcommande = $em->getRepository(Commande::class)->findOneBy([], ['id' => 'DESC']);
        $numero = $lastcommande ? intval(substr($lastcommande->getDescription(), -4)) + 1 : 1;
        $desc = 'COM-' . str_pad($numero, 3, '0', STR_PAD_LEFT);
        $commande->setDescription($desc);

        $prixcommande = 0;

        foreach ($details as $detail) {
            $detailcommande = new Detailcommande();
            $detailcommande->setDescription($detail['form']['detailcommande']['description']);
            $detailcommande->setPrix($detail['form']['detailcommande']['prix']);
            $detailcommande->setType($detail['form']['detailcommande']['type']);
            $detailcommande->setCommande($commande);
            $detailcommande->setQteconsommable($detail['form']['detailcommande']['qteconsommable']);
            $detailcommande->setQtecommande($detail['form']['detailcommande']['qtecommande']);
            $detailcommande->setDimension($detail['form']['detailcommande']['dimension']);
            $detailcommande->setCreateAlt(new \DateTime());

            // mise a jour de l'approvisionnement
            $consommable = $consommableRepository->find($detail['form']['detailcommande']['consommable']);
            $consommableQteRestant = $consommable->getQtedispo();
            if ($consommableQteRestant < $detail['form']['detailcommande']['qteconsommable']) {
                $this->addFlash('warring', 'Quantite restant est insuffisant');
            }
            $consommable->setQtedispo($consommableQteRestant - $detail['form']['detailcommande']['qteconsommable']);
            $detailcommande->setConsommable($consommable);
            $prixcommandes = $detail['form']['detailcommande']['prix'] * $detail['form']['detailcommande']['qtecommande'];
            $prixcommande = $prixcommande +  $prixcommandes;
            $em->persist($detailcommande);
        }

        $commande->setPrixcommande($prixcommande);
        $em->persist($commande);
        $em->flush();
        
        $session->remove('details_commande');
        return $this->redirectToRoute('app_detailcommande_show', ['idcommande' => $commande->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/show/{idcommande}', name: 'app_detailcommande_show', methods: ['GET', 'POST'])]
    public function show(Request $request, EntityManagerInterface $em, $idcommande, CommandeRepository $commandeRepository, ClientRepository $clientRepository, DetailcommandeRepository $detailcommandeRepository, FactureRepository $factureRepository): Response
    {
        $commande = $commandeRepository->find($idcommande);
        $detailcommande = $detailcommandeRepository->findBy(['commande' => $idcommande]);
        $client = $commande->getClient();
        $factures = $factureRepository->findBy(['Commande' => $idcommande]);
        //somme des montants du facture payer pour une commande
        $totalpayer = $factureRepository->SommeMontantPayerCommande($idcommande);

        //gestion de la facture
        $facture = new Facture();
        $form = $this->createForm(FactureType::class);
        $form->handleRequest($request);
        $commande = $em->getRepository(Commande::class)->find($idcommande);
        if ($form->isSubmitted() && $form->isValid()) {
            $facture->setCommande($commande);
            $facture->setDatefacture(new \DateTime);
            $facture->setMontant($form->get('montatalfacture')->getData());
            $facture->setMoyenpaiemant($form->get('moyenpaiement')->getData());
            $payer = $totalpayer + $form->get('montatalfacture')->getData();
            $facture->setResteapayer($commande->getPrixcommande() - $payer);
            if ($payer == $commande->getPrixcommande()) {
                $facture->setStatut('payer');
            }
            if ($payer < $commande->getPrixcommande()) {
                $facture->setStatut('avance');
            }
            $annerCreationAkemarservice = "010324";

templates/detailcommande/_delete_form.html.twig
<form method="post" action="{{ path('app_detailcommande_delete', {'id': detailcommande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ detailcommande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/detailcommande/_form.html.twig
<div class="block-content block-content-full">
  {{ form_start(form) }}

  <div class="mb-4">
    <label class="form-label" for="checkout-cc-number"
      >Description de la commande</label
    >
    {{ form_row(form.description) }}
  </div>
  <div class="mb-4">
    <label class="form-label" for="checkout-cc-name">Type de la commande</label>
    {{ form_row(form.type) }}
  </div>

  <div class="mb-4">
    <label class="form-label" for="checkout-cc-number">Quantité commandé</label>
    {{ form_row(form.qtecommande) }}
  </div>
  <div class="mb-4">
    <label class="form-label" for="checkout-cc-name">Prix unitaire</label>
    {{ form_row(form.prix) }}
  </div>
  <div class="mb-4">
    <label class="form-label" for="checkout-cc-number"
      >Consommable à utiliser</label
    >
    {{ form_row(form.consommable) }}
  </div>
  <div class="mb-4">
    <label class="form-label" for="checkout-cc-number"
      >Dimension du support</label
    >
    {{ form_row(form.dimension) }}
  </div>

  <div class="mb-4">
    <label class="form-label" for="checkout-cc-number"
      >Quantité de la commande</label
    >
    {{ form_row(form.qteconsommable) }}
  </div>
  <div class="row">
    <div class="col-6">
      <div class="mb-4">
        {{ form_row(form.autre) }}
      </div>
    </div>
    <div class="col-6">
      <div class="text-end">
        {{ form_row(form.enregister) }}
      </div>
    </div>
  </div>

  {{ form_end(form) }}
</div>

templates/detailcommande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Detailcommande{% endblock %}

{% block body %}
    <h1>Edit Detailcommande</h1>

    {{ include('detailcommande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_detailcommande_index') }}">back to list</a>

    {{ include('detailcommande/_delete_form.html.twig') }}
{% endblock %}

templates/detailcommande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detailcommande index
{% endblock %}

{% block body %}

	
	<h1>Detailcommande index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Description</th>
				<th>Type</th>
				<th>Prix</th>
				<th>Dimension</th>
				<th>CreateAlt</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for detailcommande in detailcommandes %}
				<tr>
					<td>{{ detailcommande.id }}</td>
					<td>{{ detailcommande.description }}</td>
					<td>{{ detailcommande.type }}</td>
					<td>{{ detailcommande.prix }}</td>
					<td>{{ detailcommande.dimension }}</td>
					<td>{{ detailcommande.createAlt ? detailcommande.createAlt|date('Y-m-d H:i:s') : '' }}</td>
					<td>
						<a href="{{ path('app_detailcommande_show', {'id': detailcommande.id}) }}">show</a>
						<a href="{{ path('app_detailcommande_edit', {'id': detailcommande.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="7">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_detailcommande_new') }}">Create new</a>
{% endblock %}

templates/detailcommande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Detailcommande
{% endblock %}

{% block body %}
	<div class="content">
		<div class="row">
			<div
				class="col-xl-4 ">
				<!-- Categories -->
				<div class="block block-rounded js-ecom-div-nav d-none d-xl-block">
					<div class="block-header block-header-default">
						<h3 class="block-title">
							<i class="fa fa-fw fa-boxes text-muted me-1"></i>
							Client
						</h3>
					</div>
					<div class="block-content">
						<ul class="nav nav-pills flex-column push">

							<li class="nav-item mb-1">
								<a class="nav-link d-flex justify-content-between align-items-center" href="javascript:void(0)">
									Nom et Prenom:
									{{client.nomclient}}
								</a>
							</li>
							<li class="nav-item mb-1">
								<a class="nav-link d-flex justify-content-between align-items-center" href="javascript:void(0)">
									Telephone:
									{{client.telephoneclient}}
								</a>
							</li>
							<li class="nav-item mb-1">
								<a class="nav-link d-flex justify-content-between align-items-center" href="javascript:void(0)">
									Adresse:
									{{client.adresse}}
								</a>
							</li>

						</ul>
					</div>
				</div>
				<!-- END Categories -->


			</div>
			<div class="col-xl-8 ">
				{% if app.session.get('details_commande') is not empty %}

					<!-- Shopping Cart -->
					<div class="block block-rounded js-ecom-div-cart d-none d-xl-block">
						<div class="block-header block-header-default">
							<h3 class="block-title">
								<i class="fa fa-fw fa-shopping-cart text-muted me-1"></i>
								Details commandes Enregistés
							</h3>
						</div>
						<div class="block-content">
							<table class="table table-borderless table-hover table-vcenter">
								<tbody>
									{% for detail in app.session.get('details_commande') %}
										<tr>

											<td class="text-center">
												<form action="{{path('detail_commande_delete',{'index':loop.index0,'id':client.id})}}" method="POST">
													<button type="submit">
														<i class="fa fa-times"></i>
													</button>
												</form>
											</td>

											<td>
												<a class="h6" href="be_pages_ecom_store_product.html">{{detail.form.detailcommande.description}}</a>
												<div class="fs-sm text-muted">{{detail.form.detailcommande.type}}
													/
													{{detail.form.detailcommande.qteconsommable}}</div>
											</td>
											<td class="text-end">
												<div class="fw-semibold">{{detail.form.detailcommande.prix}}</div>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
						<div class="block-content block-content-full bg-body-light text-end">
							<a class="btn btn-primary" href="{{path('app_detailcommande_save',{'id':client.id})}}">Enregistrer
								<i class="fa fa-arrow-right opacity-50 ms-1"></i>
							</a>
						</div>
					</div>
					<!-- END Shopping Cart -->
				{% endif %}

				<!-- Product -->
				<div class="block block-rounded">
					<div class="block-header block-header-default">
						<h3 class="block-title">
							<i class="fa fa-fw fa-shopping-cart text-muted me-1"></i>
							Details commandes
						</h3>
					</div>
					<div class="block-content">
						{{ include('detailcommande/_form.html.twig') }}

					</div>
				</div>
				<!-- END Product -->
			</div>
		</div>
	</div>


{% endblock %}

templates/detailcommande/show.html.twig
{% extends 'base.html.twig' %} {% block title %}Detailcommande {% endblock %} {%
block body %}
<!-- Page Content -->
<div class="content">
  <!-- Quick Overview -->
  <div class="row">
    <div class="col-6 col-lg-3">
      <a class="block block-rounded block-link-shadow text-center" href="javascript:void(0)" >
        <div class="block-content block-content-full">
          <div class="item item-circle bg-success-light mx-auto">
            <i class="fa fa-check text-success"></i>
          </div>
        </div>
        <div class="block-content py-2 bg-body-light">
          <p class="fw-medium fs-sm text-success mb-0">{{ commande.description }}</p>
        </div>
      </a>
    </div>
    
  </div>
  <!-- END Quick Overview -->

  <!-- Products -->
  <div class="block block-rounded">
    <div class="block-header block-header-default">
      <h3 class="block-title">Details commande</h3>
    </div>
    <div class="block-content">
      <div class="table-responsive">
        <table class="table table-borderless table-striped table-vcenter fs-sm">
          <thead>
            <tr>
              <th class="text-center" style="width: 100px">ID</th>
              <th>Description</th>
              <th class="text-center">Qte</th>
              <th class="text-end" style="width: 10%">Prix U.</th>
              <th class="text-end" style="width: 10%">Montant</th>
            </tr>
          </thead>
          <tbody>
            {% set total = 0 %} {% for detailcommandes in detailcommandes %}

            <tr>
              <td class="text-center">
                <a href="#">
                  <strong>{{ detailcommandes.id }}</strong>
                </a>
              </td>
              <td>
                {{ detailcommandes.description }}
              </td>
              <td class="text-center">
                <strong>{{ detailcommandes.qtecommande }}</strong>
              </td>
              <td class="text-end">{{ detailcommandes.prix }} F</td>
              <td class="text-end">
                {{ detailcommandes.qtecommande * detailcommandes.prix }} F
              </td>
            </tr>
            {% set total = total + detailcommandes.qtecommande * detailcommandes.prix %}
             {% endfor %}

            <tr>
              <td colspan="4" class="text-end">
                <strong>Montant Total:</strong>
              </td>
              <td class="text-end">{{ total }} F</td>
            </tr>
            <tr>
              <td colspan="4" class="text-end">
                <strong>Montant Total Payé :</strong>
              </td>
              <td class="text-end">{{ totalpayer }} F</td>
            </tr>
            <tr class="table-success">
              <td colspan="2" class="text-uppercase">
				{% if (total - totalpayer) == 0 %}
					
					{% else %}
					<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-block-popin">
						Ajouter
					</button>
				{% endif %}
              </td>
              <td colspan="2" class="text-end ">
                <strong>Total Due:</strong>
              </td>
              <td class="text-end">
                <strong>{{total - totalpayer }} F</strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- END Products -->

  <!-- Customer -->
  <div class="row">
    <div class="col-sm-6">
      <!-- Billing Address -->
      <div class="block block-rounded">
        <div class="block-header block-header-default">
          <h3 class="block-title">Client</h3>
        </div>
        <div class="block-content">
          <div class="fs-4 mb-1">Nom client : {{client.nomclient}}</div>
          <address class="fs-4 mb-1">
            Telephone Client : {{client.telephoneclient}}<br />
           Adresse Client : {{client.adresse}}<br /><br />
            
          </address>
        </div>
      </div>
      <!-- END Billing Address -->
    </div>
    <div class="col-sm-6">
      <!-- Shipping Address -->
      <div class="block block-rounded">
        <div class="block-header block-header-default">
          <h3 class="block-title">Les factures</h3>
        </div>
        <div class="block-content">
          <table
            class="table table-borderless table-striped"
          >
            <tbody>
              {% for facture in facture %}

              <tr>
                <td class="fs-base" >
                  {{facture.reference}}
                </td>
				<td class="text-success">{{facture.statut}}</td>
                <td>
					{{facture.montant}} F
                </td>
				<td class="text-center">
					<div class="btn-group">
					<a class="btn btn-sm btn-alt-secondary" href="{{ path('app_facture_show', {'id': facture.id,'idcommande': facture.commande.id}) }}">
						<i class="fa fa-eye"></i>
					</a>
						
					</div>
				</td>
                
              </tr>
              {% else %}
              <tr class="text-center">
                <td>Auccune facture enregistée pour cette commande</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <!-- END Shipping Address -->
    </div>
  </div>
  <!-- END Customer -->
</div>
<!-- END Page Content -->
<div
  class="modal fade"
  id="modal-block-popin"
  tabindex="-1"
  role="dialog"
  aria-labelledby="modal-block-popin"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-popin" role="document">
    <div class="modal-content">{% include "facture/_form.html.twig" %}</div>
  </div>
</div>

{% endblock %}